version: "3.9"
services:
  neo4j:
    image: datascientest/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - my_network
    volumes:
    - ~/Projet3/import:/import
  api:
    image: malekidri/api_projet3:latest
    networks:
      - my_network
    ports:
      - "8000:8000"
networks:
  my_network:
