version: "3.9"
services:
  neo4j:
    image: datascientest/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - my_network
    volumes:
    - ~/Projet3/import:/import
    healthcheck:
        test: wget http://localhost:7474 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
        start_period: 3s
  api:
    image: malekidri/api_projet3:latest
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - my_network
    ports:
      - "8000:8000"

networks:
  my_network:
